<script>
export default {
  data() {
    return {};
  },
};
</script>
<template>
  <body>
    <div class="Content"><h2>Content goes here..</h2></div>
    <div class="Selling">
      <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <div class="Items-search">
      <div>
        <h2>DC COMICS</h2>
        <ul>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
        <h2>SHOP</h2>
        <ul>
          <li>Shop DC</li>
          <li>Shop DC Collectibles</li>
        </ul>
      </div>

      <!-- <h2>DC</h2>
        <ul>
          <li>Terms Of Use</li>
          <li>Privacy policy(New)</li>
          <li>Ad Choices</li>
          <li>Advertising</li>
          <li>Jobs</li>
          <li>Subscriptions</li>
          <li>Talent Workshops</li>
          <li>CPSC certifications</li>
          <li>ratings</li>
          <li>Shop Help</li>
          <li>Contact Us</li>
        </ul>
      </div>
      <div>
        <h2>Sites</h2>
        <ul>
          <li>DC</li>
          <li>MAD Magazines</li>
          <li>DC Kids</li>
          <li>DC Universe</li>
          <li>DC Power visa</li>
        </ul>
      </div> -->
    </div>
  </body>
</template>
<style lang="scss">
body {
  height: 60vh;
  width: 100%;
  background-color: black;

  .Content {
    text-align: left;
    margin-left: 20%;
    height: 20%;

    h2 {
    }
  }

  .Selling {
    height: 30%;
    background-color: cornflowerblue;
  }
  .Items-search {
    height: 50%;
  }
}
</style>
