<script>
export default {
  data() {
    return {};
  },
};
</script>
<template>
  <div><h2>Content goes here..</h2></div>
  <div>
    <ol>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ol>
  </div>
  <div>
    <div>
      <div>
        <h2>DC COMICS</h2>
        <ol>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ol>
        <h2>SHOP</h2>
        <ol>
          <li>Shop DC</li>
          <li>Shop DC Collectibles</li>
        </ol>
      </div>
      <div>
        <H2></H2>
      </div>
      <div></div>
    </div>
  </div>
</template>
<style></style>
